### ISSUE TITLE
Name 'soup' is not defined

### ISSUE THREAD

**Issue by juanblasmdq** [egonik-unlp/dolarr_historico#1]
Buenas! Primero que nada, gracias por compartir tu trabajo! Llegué acá desde Reddit y como estoy aprendiendo algo de Python y el proyecto me pareció útil, quise probarlo.

Al correr el script me tiró el siguiente error:

`Traceback (most recent call last):
  File "C:\Users\teacej\Desktop\dolar_historico-main\script.py", line 61, in <module>
    data = main()
  File "C:\Users\teacej\Desktop\dolar_historico-main\script.py", line 54, in main
    data = parser(raw_data)
  File "C:\Users\teacej\Desktop\dolar_historico-main\script.py", line 29, in parser
    for rows in soup.find_all('tr'):
NameError: name 'soup' is not defined`

Que (pareciera) quedó solucionado al cambiar la línea:

de:
`for rows in soup.find_all('tr'):`
a:
`for rows in table.find_all('tr'):`

Te lo paso por si te sirve!
Saludos
Juan

PD: Lo estoy corriendo desde la IDE default de Python, no Jupyter

**Comment by egonik-unlp** [comment]
Muchas gracias! no me di cuenta de cambiar soup por table todas las veces que aparece! 
Ua pregunta de curiosidad, instalaste las dependencias a mano o usaste los comandos del readme?
Cualquier correccion que tengas si queres podes mandar un pull request y te lo incorporo sin problemas, sobretodo para que quede registrado que contribuiste.

Cualquier duda pregunta!

**Comment by juanblasmdq** [comment]
Eduardo, gracias a vos. Las instalé en un virtual environment desde el archivo "requirements_pip.txt" que incluiste (aunque me suena que hay bastantes cosas de más ahí).

Recién estoy aprendiendo a usar Github así que todavía no estoy seguro de como hacer el pull requests y como funciona el tema de los Forks, pero veo que ya lo cambiaste! Ahora voy a chusmear un poco más en Youtube

Sds
Juan

**Comment by egonik-unlp** [comment]
Si, están incluidas las librerias necesarias para correr el codigo en jupyter, más pensando si usas un env específico para correr el codigo (que tiene más sentido en conda). Voy a tratar de incluir un requirements más cortito.
